# Generated by Django 6.0 on 2026-01-16 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text="Unique identifier (e.g., 'annual_work_summary')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('category', models.CharField(help_text="Template category (e.g., '工作总结', '项目报告')", max_length=100)),
                ('sections_json', models.JSONField(default=dict, help_text='Template sections structure in JSON format')),
                ('template_type', models.CharField(choices=[('system', 'System Template'), ('user', 'User Template')], default='user', help_text='Whether this is a system or user template', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['-created_at'],
                'unique_together': {('template_id', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='TemplateUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user_outline', models.TextField(help_text="User's outline/key points")),
                ('had_source_document', models.BooleanField(default=False, help_text='Whether user uploaded a source document')),
                ('template_name', models.CharField(blank=True, help_text='Template name used (for reference if template is deleted)', max_length=200)),
                ('generation_success', models.BooleanField(default=True, help_text='Whether the generation was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed')),
                ('generation_duration', models.IntegerField(blank=True, help_text='Generation duration in seconds', null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='format_specifications.documenttemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Usage Log',
                'verbose_name_plural': 'Template Usage Logs',
                'ordering': ['-used_at'],
            },
        ),
    ]
